- hosts: localhost
  connection: local
  vars:
    db_name: sinatra_db
    db_user: sinatra_dev
    db_user_password: developer
    
  tasks:
    - name: postgresql | install 
      sudo: yes
      apt: pkg={{ item }} state=latest install_recommends=no
      with_items:
        - postgresql
        - python-psycopg2
        - postgresql-server-dev-9.3
        - libpq-dev

    - name: postgresql | create database
      sudo: yes
      sudo_user: postgres
      postgresql_db: name={{ db_name }}
      
    - name: postgresql | create user
      sudo: yes
      sudo_user: postgres
      postgresql_user: "db={{ db_name }} name={{ db_user }} password={{ db_user_password }} priv=ALL"

    - name: postgresql | set user premissions
      sudo: yes
      sudo_user: postgres
      postgresql_user: name="{{ db_user }}" role_attr_flags=NOSUPERUSER,NOCREATEDB